tasks:
  - before: curl https://sh.rustup.rs -sSf | sh
    before: 1
    before: source /workspace/.cargo/env
  - init: rustup install nightly
    init: rustup install stable
    init: rustup target add wasm32-unknown-unknown --toolchain nightly
    command: make init
    command: make build